### PR TITLE
Fix PlatformVersion isues

### LINKED ISSUE #18: Get-D365BCPlatformVersion does not work for newer BC Version
Runtime Packages created for BC22 or BC23 does not include the PlatformVersion Property.

### PR DESCRIPTION
**Pull request by ChrisBlankDe**
handle new json format on EmittedContent for BC23 Runtime Packages
return PlatformVersion also when using FullExtract

fixes #18

### CODE REVIEW

**Comment by SimonOfHH** [comment]
Hi @ChrisBlankDe 
thank you for your PR 😊 Just wondering: did you verify that it also still works with previously created runtime packages? Or only for v22+?

**Comment by ChrisBlankDe** [comment]
@SimonOfHH I have tested this, I just forgot to document it. ive tested runtime packages from v21, v23 and a normal v23 app package. 

Current Version vom PSGallery:
```powershell
import-module D365BCAppHelper
Get-D365BCManifestFromAppFile -Filename "C:\apps\AwesomeCorp_EvenMoreAwesomeApp_21.0.44370.0-runtime2100.app" | %{$_.App.Name ;$_.App.PlatformVersion} #EvenMoreAwesomeApp; 21.0.46384.46844
Get-D365BCManifestFromAppFile -Filename "C:\apps\AwesomeCorp_EvenMoreAwesomeApp_21.0.44370.0-runtime2100.app" -FullExtract | %{$_.App.Name ;$_.App.PlatformVersion} #EvenMoreAwesomeApp
Get-D365BCManifestFromAppFile -Filename "C:\apps\AwesomeCorp_EvenMoreAwesomeApp_23.0.30.0-runtime2300.app" | %{$_.App.Name ;$_.App.PlatformVersion} #EvenMoreAwesomeApp; ...
Get-D365BCManifestFromAppFile -Filename "C:\apps\AwesomeCorp_EvenMoreAwesomeApp_23.0.30.0-runtime2300.app" -FullExtract | %{$_.App.Name ;$_.App.PlatformVersion} #EvenMoreAwesomeApp
Get-D365BCManifestFromAppFile -Filename "C:\apps\AwesomeCorp_EvenMoreAwesomeApp_23.0.30.0.app" | %{$_.App.Name ;$_.App.PlatformVersion} #EvenMoreAwesomeApp
Get-D365BCManifestFromAppFile -Filename "C:\apps\AwesomeCorp_EvenMoreAwesomeApp_23.0.30.0.app" -FullExtract | %{$_.App.Name ;$_.App.PlatformVersion} #EvenMoreAwesomeApp
```

With this PR:
```powershell
import-module C:\git\D365BCAppHelper -Force
Get-D365BCManifestFromAppFile -Filename "C:\apps\AwesomeCorp_EvenMoreAwesomeApp_21.0.44370.0-runtime2100.app" | %{$_.App.Name ;$_.App.PlatformVersion} #EvenMoreAwesomeApp; 21.0.46384.46844
Get-D365BCManifestFromAppFile -Filename "C:\apps\AwesomeCorp_EvenMoreAwesomeApp_21.0.44370.0-runtime2100.app" -FullExtract | %{$_.App.Name ;$_.App.PlatformVersion} #EvenMoreAwesomeApp; 21.0.46384.46844
Get-D365BCManifestFromAppFile -Filename "C:\apps\AwesomeCorp_EvenMoreAwesomeApp_23.0.30.0-runtime2300.app" | %{$_.App.Name ;$_.App.PlatformVersion} #EvenMoreAwesomeApp; 23.0.12859.0
Get-D365BCManifestFromAppFile -Filename "C:\apps\AwesomeCorp_EvenMoreAwesomeApp_23.0.30.0-runtime2300.app" -FullExtract | %{$_.App.Name ;$_.App.PlatformVersion} #EvenMoreAwesomeApp; 23.0.12859.0
Get-D365BCManifestFromAppFile -Filename "C:\apps\AwesomeCorp_EvenMoreAwesomeApp_23.0.30.0.app" | %{$_.App.Name ;$_.App.PlatformVersion} #EvenMoreAwesomeApp
Get-D365BCManifestFromAppFile -Filename "C:\apps\AwesomeCorp_EvenMoreAwesomeApp_23.0.30.0.app" -FullExtract | %{$_.App.Name ;$_.App.PlatformVersion} #EvenMoreAwesomeApp
```

tested with a real app, only the names were changed

**Comment by SimonOfHH** [comment]
Hi @ChrisBlankDe ,
sorry for the delay (it was a bit busy). I just tested this as well with an older runtime-package (I think it was BC16). For that it fails. Looks like the change to `"bin/EmittedContent.json"` instead of `"EmittedContent.json"` caused this 🤔
Let me check this and get back to you

**Comment by SimonOfHH** [comment]
Sorry, forget my last remark. Looks like I used a wrong file for checking 🤦

**Pull request merged**
